license = "${license}"
issueTrackerURL="https://github.com/dexman545/Fabric-Autoswitch/issues"
[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
#see https://docs.neoforged.net/docs/misc/updatechecker/
#see https://docs.modrinth.com/api/operations/forgeupdates/
updateJSONURL="https://api.modrinth.com/updates/autoswitch/forge_updates.json?neoforge=only"
displayURL="https://modrinth.com/mod/autoswitch"
logoFile="${mod_id}.png"
credits="${credits}"
authors = "${mod_author}"
description = '''${description}'''
[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"
[[dependencies."${mod_id}"]]
modId = "neoforge"
type="required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "minecraft"
type="required"
versionRange = "${neo_mc_version_range}"
ordering = "NONE"
side = "BOTH"

[features."${mod_id}"]
javaVersion="[${java_version},)"
